// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $about_about from "./routes/about/about.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $countdown from "./routes/countdown.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $search from "./routes/search.tsx";
import * as $Countdown from "./islands/Countdown.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $Display from "./islands/Display.tsx";
import * as $Display2 from "./islands/Display2.tsx";
import * as $util from "./islands/util.tsx";
import * as $wasm_exec from "./islands/wasm_exec.js";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/about/about.tsx": $about_about,
    "./routes/api/joke.ts": $api_joke,
    "./routes/countdown.tsx": $countdown,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/search.tsx": $search,
  },
  islands: {
    "./islands/Countdown.tsx": $Countdown,
    "./islands/Counter.tsx": $Counter,
    "./islands/Display.tsx": $Display,
    "./islands/Display2.tsx": $Display2,
    "./islands/util.tsx": $util,
    "./islands/wasm_exec.js": $wasm_exec,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
